### ISSUE TITLE
It's possibile to print the battery percentage nearest the icon?

### ISSUE THREAD

**Issue by pepib** [phillid/paramano#3]
as the title.

**Comment by phillid** [comment]
Thanks for your idea, it's something I've been meaning to 'get around to' for a while now, but I'll be sure to start writing this feature in now that there is demand.

**Comment by phillid** [comment]
After doing some reading, it would seem that a status icon put in the system tray can only be made up of pixels, with **no** abstractions like windows or labels on top of this which toolkits such as GTK and QT provide. Sadly, it's not simply a matter of drawing a GTK label.

This means the only way to achieve this issue's goal would be to manually create a pixbuf using, eg, Cairo, write text to it, underlay the battery icon, and finally set the status icon to the data stored in the pixbuf. This works fine so long as the GTK theme is never changed to (eg) a dark theme. If this is the case, the icon is no longer on-theme and we achieve poor readability. In order to achieve a theme-correct text overlay, parts of the current GTK theme would have to be discovered. I don't have the knowledge at present to achieve this.

I will leave the issue open in case anyone wants to follow up, or submit a pull request etc.
